create or replace TRIGGER "TBL_LOANED_BOOKS_LIB_TRG"
BEFORE INSERT OR UPDATE OR DELETE ON "TBL_LOANED_BOOKS_LIB"
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    SELECT SEQ_LIBRARY.NEXTVAL
    INTO :NEW.LOANED_BOOKS_ID
    from TBL_LOANED_BOOKS_LIB;
  END IF;
END;
/