create or replace TRIGGER "TBL_MEMBER_LIB_TRG"
BEFORE INSERT OR UPDATE OR DELETE ON "TBL_MEMBER_LIB"
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    SELECT SEQ_LIBRARY.NEXTVAL
    INTO :NEW.MEMBER_ID
    from TBL_MEMBER_LIB;
  END IF;
END;
/